spring:

  application:
    name: service-portal-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  cloud:
    gcp:
      storage:
        bucket: ${GCS_BUCKET_NAME}

jwt:
  secret: ${JWT_SECRET}
  expiration-time: ${JWT_EXPIRATION_TIME}

media:
  max-size:
    photo: 10_485_760 #10MB
    video: 52_428_800 #50MB

  allowed-mime-types:
    - image/jpeg
    - image/png
    - image/webp
    - image/gif
    - image/heic
    - video/mp4
    - video/quicktime
    - video/webm